CREATE TABLE public.USER (
    ID VARCHAR(32),
    ALIAS VARCHAR(255),
    CONTACT_NO VARCHAR(100),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE public.ACTOR (
    ID VARCHAR(32),
    CREATED_DT TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DT TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    FULL_NAME VARCHAR(100),
    BIRTH_DT TIMESTAMP,
    DSCP TEXT
);

CREATE TABLE public.REVIEW (
    ID VARCHAR(32),
    CREATED_DT TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_DT TIMESTAMP,
    UPDATED_BY VARCHAR(255),
    MOVIE_ID VARCHAR(32),
    DSCP VARCHAR(255),
    RATING int,
    PRIMARY KEY (ID)
);